# -*- coding: utf-8 -*-
"""PythonTasks.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Lnd4G9bTePplM66ksyfu4yV9Sv8uV13Z
"""

# =====================================================
# PYTHON TASKS
# =====================================================

# INSTALL LIBRARIES
!pip install pandas numpy plotly matplotlib seaborn scikit-learn statsmodels openpyxl -q

# =====================================================
# IMPORT LIBRARIES
# =====================================================

import pandas as pd
import numpy as np
import plotly.express as px
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

from statsmodels.tsa.arima.model import ARIMA

# =====================================================
# UPLOAD DATASET
# =====================================================

from google.colab import files

uploaded = files.upload()

# =====================================================
# LOAD DATASET
# =====================================================

df = pd.read_csv(
    "DatasetSureTrust.csv",
    encoding="latin1"
)

print("Dataset Loaded Successfully")
print(df.head())

# =====================================================
# TASK 1
# Import SQL financial data into Pandas
# =====================================================

print("\n================ TASK 1 =================")
print(df.head(20))

# =====================================================
# TASK 2
# Clean and preprocess revenue data
# =====================================================

print("\n================ TASK 2 =================")

clean_df = df.copy()

clean_df.dropna(inplace=True)

clean_df.columns = clean_df.columns.str.strip()

print("Shape After Cleaning:", clean_df.shape)

print(clean_df.head())

# =====================================================
# TASK 3
# EDA on profitability trends
# =====================================================

print("\n================ TASK 3 =================")

profit_region = df.groupby("Region")["Profit"].sum().reset_index()

fig = px.bar(
    profit_region,
    x="Region",
    y="Profit",
    color="Region",
    title="Region-wise Profit Analysis"
)

fig.show()

# =====================================================
# TASK 4
# Regression models for revenue forecasting
# =====================================================

print("\n================ TASK 4 =================")

regression_df = df[["Sales", "Profit"]].dropna()

X = regression_df[["Sales"]]
y = regression_df["Profit"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

model = LinearRegression()

model.fit(X_train, y_train)

predictions = model.predict(X_test)

mse = mean_squared_error(y_test, predictions)

print("Mean Squared Error:", mse)

result_df = pd.DataFrame({
    "Actual Profit": y_test.values,
    "Predicted Profit": predictions
})

print(result_df.head())

# =====================================================
# TASK 5
# ARIMA for time-series forecasting
# =====================================================

print("\n================ TASK 5 =================")

sales_series = df["Sales"].dropna()

model = ARIMA(
    sales_series,
    order=(2,1,2)
)

model_fit = model.fit()

forecast = model_fit.forecast(steps=10)

forecast_df = pd.DataFrame({
    "Forecasted Sales": forecast
})

print(forecast_df)

fig = px.line(
    forecast_df,
    y="Forecasted Sales",
    title="Future Sales Forecast"
)

fig.show()

# =====================================================
# TASK 6
# Visualize profit margins with seaborn
# =====================================================

print("\n================ TASK 6 =================")

plt.figure(figsize=(10,5))

sns.histplot(
    df["Profit"],
    kde=True
)

plt.title("Profit Distribution")
plt.show()

# =====================================================
# TASK 7
# Automate quarterly reporting
# =====================================================

print("\n================ TASK 7 =================")

quarterly_report = df.groupby("Region")[["Sales", "Profit"]].sum()

print(quarterly_report)

# =====================================================
# TASK 8
# ML model for cost prediction
# =====================================================

print("\n================ TASK 8 =================")

ml_df = df[["Sales", "Profit", "Quantity"]].dropna()

X = ml_df[["Sales", "Quantity"]]

y = ml_df["Profit"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

model = LinearRegression()

model.fit(X_train, y_train)

predictions = model.predict(X_test)

result_df = pd.DataFrame({
    "Actual Profit": y_test.values,
    "Predicted Profit": predictions
})

print(result_df.head())

# =====================================================
# TASK 9
# Export results to CSV for Power BI
# =====================================================

print("\n================ TASK 9 =================")

export_df = df.head(100)

export_df.to_csv(
    "PowerBI_Export.csv",
    index=False
)

print("CSV Exported Successfully")

# DOWNLOAD FILE
files.download("PowerBI_Export.csv")

# =====================================================
# TASK 10
# Link Python outputs to Data Science
# =====================================================

print("\n================ TASK 10 =================")

summary_df = df.describe()

print(summary_df)

corr = df.corr(numeric_only=True)

fig = px.imshow(
    corr,
    text_auto=True,
    title="Correlation Matrix"
)

fig.show()

print("\nALL TASKS COMPLETED SUCCESSFULLY")