# -*- coding: utf-8 -*-
"""MLTasks.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ieFlxlUNWbvWXNpotXkysyINKmr99AS9
"""

# =====================================================
# INSTALL LIBRARIES
# =====================================================

!pip install pandas numpy matplotlib seaborn scikit-learn statsmodels plotly


# =====================================================
# IMPORT LIBRARIES
# =====================================================

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import (
    confusion_matrix,
    accuracy_score,
    mean_squared_error
)

from sklearn.tree import DecisionTreeClassifier

from statsmodels.tsa.arima.model import ARIMA


# =====================================================
# UPLOAD DATASET
# =====================================================

from google.colab import files

uploaded = files.upload()


# =====================================================
# LOAD DATASET
# =====================================================

df = pd.read_csv(
    "DatasetSureTrust.csv",
    encoding="latin1"
)

print("Dataset Loaded Successfully")

print(df.head())


# =====================================================
# DATA CLEANING
# =====================================================

df.dropna(inplace=True)

print("Dataset Shape :", df.shape)


# =====================================================
# TASK 1 → FEATURE ENGINEERING
# =====================================================

print("\n==============================")
print("TASK 1 → PROFIT MARGIN")
print("==============================")

df["Profit Margin"] = (
    df["Profit"] / df["Sales"]
) * 100

result = df[
    ["Sales", "Profit", "Profit Margin"]
]

print(result.head())

plt.figure(figsize=(8,5))

scatter = plt.scatter(
    df["Sales"],
    df["Profit"],
    c=df["Profit Margin"]
)

plt.colorbar(scatter)

plt.xlabel("Sales")
plt.ylabel("Profit")

plt.title("Profit Margin Drivers")

plt.show()


# =====================================================
# TASK 2 → K-MEANS CLUSTERING
# =====================================================

print("\n==============================")
print("TASK 2 → K-MEANS CLUSTERING")
print("==============================")

cluster_df = df[
    ["Sales", "Profit"]
]

model = KMeans(
    n_clusters=3,
    random_state=42
)

df["Cluster"] = model.fit_predict(cluster_df)

print(df[["Sales", "Profit", "Cluster"]].head())

plt.figure(figsize=(8,5))

sns.scatterplot(
    x=df["Sales"],
    y=df["Profit"],
    hue=df["Cluster"],
    palette="Set1"
)

plt.title("K-Means Product Segmentation")

plt.show()


# =====================================================
# TASK 3 → CLASSIFICATION MODEL
# =====================================================

print("\n==============================")
print("TASK 3 → CLASSIFICATION")
print("==============================")

df["Profit_Class"] = np.where(
    df["Profit"] > df["Profit"].median(),
    1,
    0
)

X = df[["Sales", "Quantity"]]

y = df["Profit_Class"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

clf = DecisionTreeClassifier()

clf.fit(X_train, y_train)

predictions = clf.predict(X_test)

accuracy = accuracy_score(
    y_test,
    predictions
)

print("Classification Accuracy :", round(accuracy, 2))


# =====================================================
# TASK 4 → RANDOM FOREST
# =====================================================

print("\n==============================")
print("TASK 4 → RANDOM FOREST")
print("==============================")

X = df[["Sales", "Quantity"]]

y = df["Profit"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

rf = RandomForestRegressor(
    n_estimators=100,
    random_state=42
)

rf.fit(X_train, y_train)

predictions = rf.predict(X_test)

result_df = pd.DataFrame({
    "Actual Profit": y_test.values,
    "Predicted Profit": predictions
})

print(result_df.head())


# =====================================================
# TASK 5 → PCA
# =====================================================

print("\n==============================")
print("TASK 5 → PCA")
print("==============================")

pca_df = df[
    ["Sales", "Profit", "Quantity"]
]

pca = PCA(n_components=2)

components = pca.fit_transform(pca_df)

pca_result = pd.DataFrame(
    components,
    columns=["PC1", "PC2"]
)

print(pca_result.head())

plt.figure(figsize=(8,5))

plt.scatter(
    pca_result["PC1"],
    pca_result["PC2"]
)

plt.xlabel("PC1")
plt.ylabel("PC2")

plt.title("PCA Visualization")

plt.show()


# =====================================================
# TASK 6 → CROSS VALIDATION
# =====================================================

print("\n==============================")
print("TASK 6 → CROSS VALIDATION")
print("==============================")

X = df[["Sales", "Quantity"]]

y = df["Profit"]

model = LinearRegression()

scores = cross_val_score(
    model,
    X,
    y,
    cv=5
)

print("Cross Validation Scores :")

print(scores)

print()

print("Average Score :", scores.mean())


# =====================================================
# TASK 7 → REGRESSION VS ARIMA
# =====================================================

print("\n==============================")
print("TASK 7 → REGRESSION VS ARIMA")
print("==============================")

X = df[["Sales"]]

y = df["Profit"]

reg = LinearRegression()

reg.fit(X, y)

reg_pred = reg.predict(X)

reg_mse = mean_squared_error(
    y,
    reg_pred
)

print("Regression MSE :", reg_mse)

sales_series = df["Sales"]

arima_model = ARIMA(
    sales_series,
    order=(2,1,2)
)

arima_fit = arima_model.fit()

forecast = arima_fit.forecast(steps=10)

print("\nARIMA Forecast :")

print(forecast)


# =====================================================
# TASK 8 → CONFUSION MATRIX
# =====================================================

print("\n==============================")
print("TASK 8 → CONFUSION MATRIX")
print("==============================")

df["Profit_Class"] = np.where(
    df["Profit"] > df["Profit"].median(),
    1,
    0
)

X = df[["Sales", "Quantity"]]

y = df["Profit_Class"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

clf = DecisionTreeClassifier()

clf.fit(X_train, y_train)

pred = clf.predict(X_test)

cm = confusion_matrix(
    y_test,
    pred
)

plt.figure(figsize=(6,4))

sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    cmap="Blues"
)

plt.title("Confusion Matrix")

plt.xlabel("Predicted")
plt.ylabel("Actual")

plt.show()


# =====================================================
# TASK 9 → CFO INSIGHTS
# =====================================================

print("\n==============================")
print("TASK 9 → CFO INSIGHTS")
print("==============================")

total_sales = df["Sales"].sum()

total_profit = df["Profit"].sum()

avg_profit = df["Profit"].mean()

print("Total Sales :", round(total_sales, 2))

print("Total Profit :", round(total_profit, 2))

print("Average Profit :", round(avg_profit, 2))


# =====================================================
# TASK 10 → EXPORT CSV
# =====================================================

print("\n==============================")
print("TASK 10 → EXPORT CSV")
print("==============================")

export_df = df.head(100)

export_df.to_csv(
    "PowerBI_Advanced_Export.csv",
    index=False
)

print("CSV Exported Successfully")


# =====================================================
# DOWNLOAD CSV
# =====================================================

files.download(
    "PowerBI_Advanced_Export.csv"
)

